# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocxtui < Formula
  desc "A terminal UI to inspect and edit OpenCode agent profiles."
  homepage "https://github.com/vherrera1991/ocxtui"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vherrera1991/ocxtui/releases/download/v0.2.0/ocxtui_0.2.0_darwin_amd64.tar.gz"
      sha256 "00434fd8e0ae90b1066d8fa1eb688cd7385e35d8ed0d8967a9475242b052a9a0"

      define_method(:install) do
        bin.install "ocxtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vherrera1991/ocxtui/releases/download/v0.2.0/ocxtui_0.2.0_darwin_arm64.tar.gz"
      sha256 "b2aca20e4878223aaf41259956b15dc8d5b06efb810299a938e087a050fefa54"

      define_method(:install) do
        bin.install "ocxtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vherrera1991/ocxtui/releases/download/v0.2.0/ocxtui_0.2.0_linux_amd64.tar.gz"
      sha256 "3463880fbb8d6edee35b9d3e949a0424ac91f6199c3a0435fc2be9d3abf359dd"
      define_method(:install) do
        bin.install "ocxtui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vherrera1991/ocxtui/releases/download/v0.2.0/ocxtui_0.2.0_linux_arm64.tar.gz"
      sha256 "bb5e7b4dd2fb2026876c9e471f8558dc318a6465d9af2ceaf0a47941cbeb5bab"
      define_method(:install) do
        bin.install "ocxtui"
      end
    end
  end

  test do
    system "#{bin}/ocxtui --help"
  end
end
