# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocxtui < Formula
  desc "A terminal UI to inspect and edit OpenCode agent profiles."
  homepage "https://github.com/vherrera1991/ocxtui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vherrera1991/ocxtui/releases/download/v0.1.0/ocxtui_0.1.0_darwin_amd64.tar.gz"
      sha256 "3c5cb1e76cce68218a9e111aa75a57db8b18a6b6bb1e6ab90f351384bed71c89"

      define_method(:install) do
        bin.install "ocxtui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vherrera1991/ocxtui/releases/download/v0.1.0/ocxtui_0.1.0_darwin_arm64.tar.gz"
      sha256 "2a4b29d42ec631e8d87a13f99aac75bdb82eec6b6ed7aff3a851dc5f25295475"

      define_method(:install) do
        bin.install "ocxtui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vherrera1991/ocxtui/releases/download/v0.1.0/ocxtui_0.1.0_linux_amd64.tar.gz"
      sha256 "5c391cf710e495a146ce02c8bb9388db6589fda6f28e1d66006839310c650334"
      define_method(:install) do
        bin.install "ocxtui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vherrera1991/ocxtui/releases/download/v0.1.0/ocxtui_0.1.0_linux_arm64.tar.gz"
      sha256 "2bd51d6a33d75ada2925cb972be98874b276d55e00ccbf92032fab96d0890e29"
      define_method(:install) do
        bin.install "ocxtui"
      end
    end
  end

  test do
    system "#{bin}/ocxtui --help"
  end
end
